/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "EventList": {
      "events": {
        "CADE": {
          "abbreviation": string
          "date": {
            "end": string
            "start": string
          }
          "format": string
          "importantDates": {
            "abstract": string
            "notification": string
            "paper": string
            "rebuttal": string
          }
          "location": string
          "name": string
          "tags": any
          "type": "conference"
          "url": string
        }
        "FoSSaCS": {
          "abbreviation": string
          "date": {
            "end": string
            "start": string
          }
          "importantDates": {
            "abstract": string
            "notification": string
            "paper": string
          }
          "location": string
          "name": string
          "tags": any
          "type": "conference"
          "url": string
        }
        "ICFP": {
          "abbreviation": string
          "date": {
            "end": string
            "start": string
          }
          "importantDates": {
            "camera-ready": string
            "conditional-acceptance": string
            "notification": string
            "paper": string
            "rebuttal": string
            "revisions": string
          }
          "location": string
          "name": string
          "tags": any
          "type": "conference"
          "url": string
        }
        "ICLP": {
          "abbreviation": string
          "date": {
            "end": string
            "start": string
          }
          "format": string
          "importantDates": {
          }
          "location": string
          "name": string
          "tags": any
          "type": "conference"
        }
        "ITP": {
          "abbreviation": string
          "date": {
            "end": string
            "start": string
          }
          "importantDates": {
          }
          "location": string
          "name": string
          "tags": any
          "type": "conference"
          "url": string
        }
        "LFMTP": {
          "abbreviation": string
          "date": {
            "end": string
            "start": string
          }
          "format": string
          "importantDates": {
          }
          "location": string
          "name": string
          "tags": any
          "type": "workshop"
          "url": string
        }
        "LICS": {
          "abbreviation": string
          "date": {
            "end": string
            "start": string
          }
          "format": string
          "importantDates": {
            "abstract": string
            "notification": string
            "paper": string
            "rebuttal": string
          }
          "location": string
          "name": string
          "tags": any
          "type": "conference"
          "url": string
        }
        "PPDP": {
          "abbreviation": string
          "date": {
            "end": string
            "start": string
          }
          "format": string
          "importantDates": {
          }
          "location": string
          "name": string
          "tags": any
          "type": "conference"
        }
        "TYPES": {
          "abbreviation": string
          "date": {
            "end": string
            "start": string
          }
          "format": string
          "importantDates": {
            "abstract": string
            "notification": string
          }
          "location": string
          "name": string
          "tags": any
          "type": "conference"
          "url": string
        }
      }
      "type": "sst.sst.Linkable"
    }
    "OpenApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PLConf": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "TimeCheck": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
