import { ScheduledEvent } from "@pl-conf/core";
import { format } from "date-fns";
import { exec } from "node:child_process";
import { lstat, mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as YAML from "yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = join(__dirname, "..");
const DATA_DIR = join(ROOT_DIR, "data");
const OUTPUT_DIR = join(ROOT_DIR, "generated");

function duplicates(values: {
  [k: string]: string;
}): { date: string; names: string[] }[] {
  const seen = new Map<string, string[]>();
  for (const [dateName, date] of Object.entries(values)) {
    const curr = seen.get(date);
    if (curr !== undefined) {
      seen.set(date, [...curr, dateName]);
    } else {
      seen.set(date, [dateName]);
    }
  }
  return [...seen.entries()]
    .filter(([, v]) => v.length > 1)
    .map(([k, v]) => ({
      date: k,
      names: v,
    }));
}

async function lastUpdatedDate(fileName: string): Promise<string> {
  return new Promise((resolve, reject) => {
    exec(`git log -1 --pretty="format:%cs" ${fileName}`, (error, stdout) => {
      if (error) {
        reject(error);
      } else {
        if (stdout === "") {
          console.warn(`No git history for ${fileName}, using current date`);
          resolve(format(new Date(), "yyyy-MM-dd"));
        } else {
          resolve(stdout);
        }
      }
    });
  });
}

async function fromYamlFile(fileName: string): Promise<ScheduledEvent> {
  const yaml = await readFile(fileName, "utf8");
  const lastUpdated = await lastUpdatedDate(fileName);
  const data = YAML.parse(yaml);
  const parseRes = ScheduledEvent.safeParse({
    ...data,
    lastUpdated,
  });
  if (parseRes.success === false) {
    throw new Error(
      parseRes.error.errors
        .map((e) => `${fileName} ${e.path}: ${e.message}`)
        .join("\n")
    );
  } else {
    const dupes = duplicates(parseRes.data.importantDates);
    if (dupes.length > 0) {
      const duplicateListings = dupes
        .map(({ date: value, names }) => `${value}: ${names.join(", ")}`)
        .join("\n");
      console.warn(
        `Found duplicated values for the important dates in ${parseRes.data.abbreviation}.\n${duplicateListings}\nDouble check these are not a copy paste mistake.`
      );
    }
    return parseRes.data;
  }
}

async function loadEvents(): Promise<Record<string, ScheduledEvent>> {
  const conferenceYears = (await readdir(DATA_DIR)).map(async (entry) => {
    const stats = await lstat(join(DATA_DIR, entry));
    return stats.isDirectory() ? [entry] : [];
  });
  const conferences: ScheduledEvent[][] = await Promise.all(
    (await Promise.all(conferenceYears)).flat().map(async (yearDir) => {
      const conferenceFiles = await readdir(join(DATA_DIR, yearDir));
      const res = await Promise.all(
        conferenceFiles.map(async (fileName) =>
          fromYamlFile(join(DATA_DIR, yearDir, fileName))
        )
      );
      return res;
    })
  );
  return Object.fromEntries(conferences.flat().map((c) => [c.abbreviation, c]));
}

async function main() {
  console.log("Loading events from YAML files...");
  const events = await loadEvents();
  const eventCount = Object.keys(events).length;
  console.log(`Loaded ${eventCount} events`);

  await mkdir(OUTPUT_DIR, { recursive: true });

  const tsContent = `// This file is auto-generated by scripts/generate-events.ts
// Do not edit manually

import type { ScheduledEvent } from "@pl-conf/core";

export const events: Record<string, ScheduledEvent> = ${JSON.stringify(events, null, 2)};
`;

  await writeFile(join(OUTPUT_DIR, "events.ts"), tsContent);
  console.log(`Written ${OUTPUT_DIR}/events.ts`);

  await writeFile(
    join(OUTPUT_DIR, "events.json"),
    JSON.stringify(events, null, 2)
  );
  console.log(`Written ${OUTPUT_DIR}/events.json`);
}

main().catch((err) => {
  console.error("Failed to generate events:", err);
  process.exit(1);
});
